---
title: "\"GoTo <labelname>\" ist ungültig, da \"<labelname>\" sich innerhalb einer Try-, Catch- oder Finally-Anweisung befindet, die diese Anweisung nicht enthält"
ms.date: 07/20/2015
f1_keywords:
- bc30754
- vbc30754
helpviewer_keywords:
- BC30754
ms.assetid: 2eefc7fb-fdf0-41e9-bf60-c3bc93580e14
ms.openlocfilehash: 4b4e1428db51276ea015b6bff5337d280e05481f
ms.sourcegitcommit: bf5c5850654187705bc94cc40ebfb62fe346ab02
ms.translationtype: MT
ms.contentlocale: de-DE
ms.lasthandoff: 09/23/2020
ms.locfileid: "91099852"
---
# <a name="goto-labelname-is-not-valid-because-labelname-is-inside-a-try-catch-or-finally-statement-that-does-not-contain-this-statement"></a>"GoTo \<labelname>" ist ungültig, da "\<labelname>" sich innerhalb einer Try-, Catch- oder Finally-Anweisung befindet, die diese Anweisung nicht enthält

Sie können nicht in einen `Try...Catch...Finally` -Block verzweigen.  
  
 **Fehler-ID:** BC30754  
  
## <a name="to-correct-this-error"></a>So beheben Sie diesen Fehler  
  
- Strukturieren Sie Ihren Code so um, dass die Beschriftung dem `Try...Catch...Finally` -Block vorangeht.  
  
## <a name="see-also"></a>Siehe auch

- [Try... Catch... Abschließend-Anweisung](../language-reference/statements/try-catch-finally-statement.md)
